blog/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<category_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^link/$', views.LinkView.as_view(),  name='link'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ]

chenblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.views import IndexView as IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import AbstractUser, User
from django.utils import timezone
from django.conf import settings


# Create your models here.


# 文章模型
class Article(models.Model):
    STATUS_CHOICES = (
        ('p', '发布'),
        ('t', '草稿'),
        ('d', '删除'),
    )
    title = models.CharField('标题', max_length=100)
    body = models.TextField('文章显示')
    text = models.TextField('原文', default='')
    description = models.CharField('摘要', max_length=140, blank=True, null=True,
                                   help_text='可选，为空则自动选取前140个字符')
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    tag = models.ManyToManyField('Tag', verbose_name='标签', blank=True)
    category = models.ForeignKey('Category', verbose_name='分类', blank=True, null=True, on_delete=models.SET_NULL)
    status = models.CharField('状态', max_length=1, choices=STATUS_CHOICES, default='p')
    time_create = models.DateTimeField('发布时间', default=timezone.now)
    time_last_modified = models.DateTimeField('修改时间', auto_now=True)
    views = models.PositiveIntegerField('浏览量', default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-time_create']
        verbose_name = '文章数据'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        """获取文章地址"""
        return reverse('blog:detail', kwargs={'article_id': self.pk})

    def status_ico(self):
        """后台发布状态的图标"""
        img = 'sign-check.png'
        if self.status == 'd':
            img = 'sign-error.png'
        elif self.status == 't':
            img = 'sign-warning.png'
        return '<img src="/static/images/%s">' % img

    status_ico.allow_tags = True
    status_ico.admin_order_field = 'status'
    status_ico.short_description = "状态"

    # def save(self,  *args, **kwargs):
    #     """文章描述的截取"""
    #     self.description = self.description or self.body[:140]
    #     super().save(*args, **kwargs)

    def viewed(self):
        """浏览量加1"""
        self.views += 1
        self.save(update_fields=['views'])

    def get_previous_article(self):
        """获取上一篇文章"""
        all_item = Article.objects.filter(status='p').order_by('id')
        index = 0
        for x in all_item:
            if x.id == self.id:
                break
            else:
                index += 1
        if index:
            return all_item[index - 1]

    def get_next_article(self):
        """获取下一篇文章"""
        all_item = Article.objects.filter(status='p').order_by('-id')
        index = 0
        for x in all_item:
            if x.id == self.id:
                break
            else:
                index += 1
        if index:
            return all_item[index - 1]


# 分类模型
class Category(models.Model):
    title = models.CharField('标题', max_length=40)
    order = models.IntegerField('排序', default=0)
    description = models.CharField('摘要', max_length=140, blank=True, null=True, default='一个分类')
    # img = models.CharField('图片地址', default='/static/category/django.png', max_length=240)
    img = models.ImageField('图片', upload_to='category/img/%Y/%m', max_length=240, )
    time_create = models.DateTimeField('创建时间', default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-time_create']
        verbose_name = '分类数据'
        verbose_name_plural = verbose_name

    def img_ico(self):
        """分类图片"""
        return '<img src="/blog/media/%s" height="40px" width="100">' % self.img

    img_ico.allow_tags = True
    img_ico.admin_order_field = 'img'
    img_ico.short_description = "图片"

    def p_count(self):
        """分类下发布状态的文章数量"""
        count = self.article_set.filter(status='p').count()
        return count


# 标签模型
class Tag(models.Model):
    title = models.CharField('标题', max_length=40)
    order = models.IntegerField('排序', default=0)
    time_create = models.DateTimeField('创建时间', default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-time_create']
        verbose_name = '标签数据'
        verbose_name_plural = verbose_name


# 导航模型
class Nav(models.Model):
    title = models.CharField('标题', max_length=40)
    url = models.CharField('URL地址', max_length=240)
    order = models.IntegerField('排序', default=0)
    time_create = models.DateTimeField('创建时间', default=timezone.now)
    is_show = models.BooleanField('显示', default=True, help_text='选择是否在菜单显示，默认显示')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-time_create']
        verbose_name = '导航数据'
        verbose_name_plural = verbose_name


class Link(models.Model):
    title = models.CharField('网站标题', max_length=100)
    url = models.URLField('网站链接', default='http://')
    description = models.CharField('网站描述', max_length=240, help_text='网站描述，240字以内', blank=True)
    order = models.PositiveIntegerField('排序', default=0)
    time_create = models.DateTimeField('创建时间', default=timezone.now)
    views = models.PositiveIntegerField('访问次数', default=0)
    is_show = models.BooleanField('显示', default=True, help_text='选择是否显示，默认显示')

    def __str__(self):
        return self.title

    def viewed(self):
        """浏览量加1"""
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        ordering = ['-time_create']
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

blog/views.py
from django.shortcuts import render
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import View
from blog.models import Article, Category, Tag, Link
from django.conf import settings
from django.http import HttpResponseRedirect

# Create your views here.


# 首页视图
class IndexView(ListView):
    template_name = 'blog/list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        articles = Article.objects.filter(status='p')
        return articles

    def get_context_data(self, **kwargs):
        kwargs['title'] = '首页'
        return super(IndexView, self).get_context_data(**kwargs)


# 分类视图
class CategoryView(ListView):
    template_name = 'blog/list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        category_id = int(self.kwargs['category_id'])
        if category_id == 0:
            articles = Article.objects.filter(category__isnull=True, status='p')
        else:
            articles = Article.objects.filter(category=category_id, status='p')
        return articles

    def get_context_data(self, **kwargs):
        try:
            kwargs['title'] = '分类:' + Category.objects.filter(pk=self.kwargs['category_id'])[0].title
        except IndexError:
            kwargs['title'] = '没有找到这个分类!'
        return super(CategoryView, self).get_context_data(**kwargs)


# 标签视图
class TagView(ListView):
    template_name = 'blog/list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        articles = Article.objects.filter(tag=self.kwargs['tag_id'], status='p')
        return articles

    def get_context_data(self, **kwargs):
        try:
            kwargs['title'] = '标签:' + Tag.objects.filter(pk=self.kwargs['tag_id'])[0].title
        except IndexError:
            kwargs['title'] = '没有找到标签!'
        return super(TagView, self).get_context_data(**kwargs)


# 搜索视图
class SearchView(ListView):
    template_name = 'blog/search.html'
    context_object_name = 'articles'

    def get_queryset(self):
        query = self.request.GET['query']
        articles = Article.objects.filter(status='p').filter(Q(body__contains=query) |
                                          Q(title__contains=query) |
                                          Q(description__contains=query))
        return articles

    def get_context_data(self, **kwargs):
        kwargs['title'] = '搜索:' + self.request.GET['query']
        kwargs['query'] = self.request.GET['query']
        return super(SearchView, self).get_context_data(**kwargs)


# 文章详情视图
class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'

    def get_object(self):
        obj = super(ArticleDetailView, self).get_object()
        if obj.status == 'p':
            obj.viewed()
            return obj

    def get_context_data(self, **kwargs):
        kwargs['title'] = super(ArticleDetailView, self).get_object().title
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class LinkView(View):
    def get(self, *args, **kwargs):
        url = '/'
        link_id = self.request.GET.get('link', 0)
        try:
                    obj = Link.objects.filter(id=link_id)[0]
                    obj.viewed()
                    url = obj.url
        except Exception:
            pass
        return HttpResponseRedirect(url)

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <meta name="theme-color" content="#eee">
    <meta name="msapplication-TileColor" content="#eee">
    <title>{% block title %}{% endblock %}-{{ SITE_NAME|default:_('ChenBlog') }}</title>
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/blog.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/prism/prism.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/code/github.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<header id="header">
    <div class="jumbotron">
        <h2>{{ SITE_MASTER }}</h2>
        <span>{{ SITE_SIGNATURE }}</span>
        <br><br>
        <nav id="nav" class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">{{ SITE_NAME }}</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="/blog">首页</a></li>
                        {% for li in nav %}
                            <li><a href="{{ li.url }}">{{ li.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
</header>

{% block container %}
{% endblock %}

<footer id="footer">
    <span>ChenBlog Powered by <a href="http://www.woodcoding.com">woodcoding</a></span><br>
    <span>Copyright&copy;{{ SITE_MASTER }} All rights reseved.</span>
</footer>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/js/prism/prism.js' %}"></script>
{% if COLORTAG %}
    <script src="{% static 'blog/js/plugins/colortags.js' %}"></script>
{% endif %}
{% block script %}{% endblock %}
</body>
</html>

blog/templates/blog/base_container.html
{% extends 'blog/base.html' %}
{% block container %}
    <div id="container">
        <div class="row container-all">
            <div class="col-sm-8 container-left">
                {% block content %}内容区{% endblock %}
            </div>
            <div class="col-sm-4 container-right">
                {% include 'blog/tools.html' %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base_container.html' %}
{% block title %}
    {{ title|default:'无标题' }}
{% endblock %}
{{ title|default:'无标题' }}
{% block content %}
    {% if article %}
        <div class="panel panel-default">
            <div class="panel-heading text-center panel-title">
                <strong>
                    {{ article.title }}
                </strong>
            </div>
            <div class="panel-body">
                <div class="article-info text-center">
                    <span class="glyphicon glyphicon-bookmark article-icon">  </span>
                    {% if article.category %}
                        <a class="category-link"
                           href="{% url 'blog:category' article.category_id %}">{{ article.category }}</a>
                    {% else %}
                        <a class="category-link" href="{% url 'blog:category' 0 %}">未分类</a>
                    {% endif %}
                    <span class="glyphicon glyphicon-time article-icon">  </span> {{ article.time_last_modified|date:"Y-m-d H:i" }}
                    <span class="glyphicon glyphicon-user article-icon">  </span> {{ article.author.username }}
                    <span class="glyphicon glyphicon-eye-open article-icon">  </span> {{ article.views }}
                </div>
                <div class="article">
                    {{ article.body|safe }}
                    {% if article.tag.all %}
                        <br><br>
                        <span class="glyphicon glyphicon-tags"></span>
                        {% for tag in article.tag.all %}
                            <a href="{% url 'blog:tag' tag.id %}"><span class="label label-default">{{ tag }}</span>
                            </a>
                        {% endfor %}
                        <br>
                    {% endif %}
                    <br>
                    <div class="alert alert-warning" role="alert">
                        版权所有,本文作者: <a href="">{{ article.author.username }}</a><br>
                        转载请注明出处: <a href="{{ request.scheme }}://{{ request.get_host }}{{ article.get_absolute_url }}">
                        {{ request.scheme }}://{{ request.get_host }}{{ article.get_absolute_url }}</a>
                    </div>
                </div>
            </div>
        </div>
        <nav>
            <ul class="pager">
                {% if article.get_previous_article %}
                    {% with article.get_previous_article as previous %}
                        <li class="previous"><a
                                href="{{ previous.get_absolute_url }}">上一篇:{{ previous.title|truncatechars:20 }}</a>
                        </li>
                    {% endwith %}
                {% endif %}
                {% if article.get_next_article %}
                    {% with article.get_next_article as next %}
                        <li class="next"><a href="{{ next.get_absolute_url }}">下一篇:{{ next.title|truncatechars:20 }}</a>
                        </li>
                    {% endwith %}
                {% endif %}
            </ul>
        </nav>
        {% include 'blog/duoshuo.html' %}
    {% else %}
        <div class="alert alert-warning" role="alert">文章不存在！</div>
    {% endif %}
{% endblock %}

blog/templates/blog/duoshuo.html
<!-- 多说评论框 start -->
	<div class="ds-thread"
         data-thread-key="{{ article.id }}"
         data-title="{{ article.title }}{% if flatpage.title %}{{ flatpage.title }}{% endif %}"
         data-url="{{ request.scheme }}://{{ request.get_host }}{{ article.get_absolute_url }}{% if flatpage.get_absolute_url %}{{ flatpage.get_absolute_url }}{% endif %}">
    </div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"{{ DUOSHUO_SHORT_NAME }}"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0]
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->

blog/templates/blog/list.html
{% extends 'blog/list_base.html' %}
{% block paginate %}
    {% include 'blog/paginate.html' %}
{% endblock %}

blog/templates/blog/list_base.html
{% extends 'blog/base_container.html' %}
{% block title %}
    {{ title|default:'无标题' }}
{% endblock %}
{% block content %}
    {% block info %}
    {% endblock %}
    {% load blog_paginate %}
    {% paginate articles paginate_num %}
    {% if articles %}
        {% for article in articles %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        {% if article.category %}
                            <a class="label label-info category" href="{% url 'blog:category' article.category_id %}">
                                {{ article.category }}
                            </a>
                        {% else %}
                            <a class="label label-info category" href="{% url 'blog:category' 0 %}">
                                未分类
                            </a>
                        {% endif %}

                        <i class="ease"></i>
                        <a href="{% url 'blog:detail' article.pk %}" class="article-title">{{ article.title }}</a>
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="article-info">
                        <span class="glyphicon glyphicon-time article-icon">  </span> {{ article.time_last_modified|date:"Y-m-d H:i" }}
                        <span class="glyphicon glyphicon-user article-icon">  </span> {{ article.author.username }}
                        <span class="glyphicon glyphicon-eye-open article-icon">  </span> {{ article.views }}
                    </div>
                    <div class="article">
                        {{ article.description|striptags|safe|truncatechars:140|linebreaks }}...
                        <a href="{% url 'blog:detail' article.pk %}" class="pull-right">继续阅读 »</a>
                    </div>
                </div>
                {% if article.tag.all %}
                    <div class="panel-footer article-footer">
                        {% for tag in article.tag.all %}
                            <a href="{% url 'blog:tag' tag.id %}">
                                <span class="label label-default">{{ tag }}</span>
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-warning" role="alert">什么东东都没有哦！</div>
    {% endif %}
    {% block paginate %}
    {% endblock %}
{% endblock %}

blog/templates/blog/paginate.html
<nav>
    <ul class="pager">
        {% if articles.has_previous %}
            <li class="previous"><a href="?page={{ articles.previous_page_number }}">上一页</a></li>
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li>
        {% endif %}
    <ul class="pagination">
        {% if current_page == first_page %}
            <li class="active"><a href="#">1<span class="sr-only">(current)</span></a></a></li>
        {% else %}
            <li><a href="?page=1">1</a></li>
        {% endif %}
        {% if pages_first > 2 %}
            <li><a href="#">...</a></li>
        {% endif %}
        {% for page in pages %}
            {% if page == current_page %}
                <li class="active"><a href="#">{{ page }}<span class="sr-only">(current)</span></a></li>
            {% else %}
                <li><a href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        {% if pages_last < last_page %}
            <li><a href="#">...</a></li>
        {% endif %}
        {% if last_page != 1 %}
            {% if last_page == current_page %}
                <li class="active"><a href="#">{{ last_page }}<span class="sr-only">(ggcurrent)</span></a></li>
            {% else %}
                <li><a href="?page={{ last_page }}">{{ last_page }}</a></li>
            {% endif %}
        {% endif %}
    </ul>
        {% if articles.has_next %}
            <li class="next"><a href="?page={{ articles.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
    </ul>
</nav>

blog/templates/blog/paginate_search.html
<nav>
    <ul class="pager">
        {% if articles.has_previous %}
            <li class="previous"><a href="?query={{ query }}&page={{ articles.previous_page_number }}">上一页</a></li>
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li>
        {% endif %}
    <ul class="pagination">
        {% if current_page == first_page %}
            <li class="active"><a href="#">1<span class="sr-only">(current)</span></a></a></li>
        {% else %}
            <li><a href="?query={{ query }}&page=1">1</a></li>
        {% endif %}
        {% if pages_first > 2 %}
            <li><a href="#">...</a></li>
        {% endif %}
        {% for page in pages %}
            {% if page == current_page %}
                <li class="active"><a href="#">{{ page }}<span class="sr-only">(current)</span></a></li>
            {% else %}
                <li><a href="?query={{ query }}&page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        {% if pages_last < last_page %}
            <li><a href="#">...</a></li>
        {% endif %}
        {% if last_page != 1 %}
            {% if last_page == current_page %}
                <li class="active"><a href="#">{{ last_page }}<span class="sr-only">(ggcurrent)</span></a></li>
            {% else %}
                <li><a href="?query={{ query }}&page={{ last_page }}">{{ last_page }}</a></li>
            {% endif %}
        {% endif %}
    </ul>
        {% if articles.has_next %}
            <li class="next"><a href="?query={{ query }}&page={{ articles.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
    </ul>
</nav>

blog/templates/blog/search.html
{% extends 'blog/list_base.html' %}
{% block info %}
    <div class="alert alert-success" role="alert">
            <h3>搜索:“{{ query }}”的结果-共{{ articles.count }}条记录</h3>
    </div>
{% endblock %}
{% block paginate %}
    {% include 'blog/paginate_search.html' %}
{% endblock %}

blog/templates/blog/temp.html
{% extends 'blog/base.html' %}
{% block content %}
    {% if article %}
    {% else %}
        <div class="alert alert-warning" role="alert">文章不存在！</div>
    {% endif %}
{% endblock %}

blog/templates/blog/tools.html
<form method="get" action="{% url 'blog:search' %}">
    <div class="input-group search-group">
        <input type="text" name="query" class="form-control" placeholder="搜索一下？">
      <span class="input-group-btn">
        <button class="btn btn-info" type="submit"><span class="glyphicon glyphicon-search"> </span> </button>
      </span>
    </div><!-- /input-group -->
</form>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">文章分类</h3>
    </div>
    {% if categories %}
        <ul class="list-group">
            {% if null_count > 0 %}
                <a class="list-group-item" href="{% url 'blog:category' 0 %}">
                    <span class="badge">{{ null_count }}</span>
                    未分类
                </a>
            {% endif %}
            {% for category in categories %}
                <a class="list-group-item" href="{% url 'blog:category' category.pk %}">
                    <span class="badge">{{ category.p_count }}</span>
                    {{ category }}
                </a>
            {% endfor %}
        </ul>
    {% else %}
        <div class="panel-body">没有分类！</div>
    {% endif %}
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">标签列表</h3>
    </div>
    <div class="panel-body">
        {% if tags %}
            {% for tag in tags %}
                <a href="{% url 'blog:tag' tag.pk %}" class="btn btn-default btn-sm tag" role="button">{{ tag }}</a>
            {% endfor %}
        {% else %}
            没有标签！
        {% endif %}
    </div>
</div>
{% if FRIENDLINK %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">友情链接</h3>
        </div>
        <div class="panel-body">
            {% if links %}
                {% for link in links %}
                    <a href="{% url 'blog:link' %}?link={{ link.pk }}" class="btn btn-default btn-sm tag" role="button">{{ link }}</a>
                {% endfor %}
            {% else %}
                没有链接！
            {% endif %}
        </div>
    </div>
{% endif %}
{% if DUOSHUO_NEW_COMMENTS %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">最新评论</h3>
        </div>
        <div class="panel-body">
            <!-- 多说最新评论 start -->
            <div class="ds-recent-comments" data-num-items="5" data-show-avatars="1" data-show-time="1"
                 data-show-title="1"
                 data-show-admin="1" data-excerpt-length="70"></div>
            <!-- 多说最新评论 end -->
            <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
            <script type="text/javascript">
                var duoshuoQuery = {short_name: "{{ DUOSHUO_SHORT_NAME }}"};
                (function () {
                    var ds = document.createElement('script');
                    ds.type = 'text/javascript';
                    ds.async = true;
                    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
                    ds.charset = 'UTF-8';
                    (document.getElementsByTagName('head')[0]
                    || document.getElementsByTagName('body')[0]).appendChild(ds);
                })();
            </script>
            <!-- 多说公共JS代码 end -->
        </div>
    </div>
{% endif %}